version: '3.8'

services:
  rimo-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rimo-prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

